/**
 * Server component wrapper for the static export.
 *
 * The client component cannot export `generateStaticParams`, so the param set is
 * declared here. `EXPORT_ID` exists only to satisfy the export; the real id comes
 * from the URL, read on the client.
 *
 * The read has to happen client-side. This file is a server component - that is
 * what allows it to export `generateStaticParams` - and a server component cannot
 * read the pathname, because the URL is not part of anything it is given at build
 * time. So `IdFromUrl` is a client component that resolves the segment and hands
 * it to the view.
 *
 * Generated by `scripts/split-dynamic-routes.mjs` - do not edit by hand.
 */
import { EXPORT_ID } from "@/lib/export-params";
import IdFromUrl from "./id-from-url";

export function generateStaticParams() {
  return [{ id: EXPORT_ID }];
}

export default function Page() {
  return <IdFromUrl />;
}
